version: '3.8'

networks:
  go:
    driver: bridge

services:
  go:
    image: go-app
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    command: ["/usr/local/bin/app"]
    networks:
      - go