name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      go-version: '1.21'

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      docker-image: 'joaowillamy/go-service:latest'
      cache-key: ${{ needs.setup.outputs.cache-key }}
      docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker-password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  # deploy:
  #   needs: [test, build]
  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     aws-region: 'us-east-1'
  #     ecs-cluster: 'main-cluster'
  #     ecs-service: 'go-service'