name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      go-version: '1.21'

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      docker-image: 'joaowillamy/go-service:latest'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    needs: [test, build]
    uses: ./.github/workflows/deploy.yml
    with:
      aws-region: 'us-east-1'
      ecs-cluster: 'main-cluster'
      ecs-service: 'go-service'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}