name: Run Tests

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ inputs.cache-key }}

    - name: Run tests
      run: go test ./...